//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class React
    {
        public int Id { get; set; }
        public Nullable<int> React1 { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IdeaId { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
    }
}
